-- Снимок рейтинга Forsaken Dungeons+: node tools/sync.js
-- Руками не править.
ForsakenIODB = {
  generatedAt = "2026-10-03T01:24:42Z",
  season = {
    id = "season-2",
    name = "Season II",
    startsOn = "01.07.2026",
    endsOn = "30.09.2026",
    phase = "interseason",
  },
  count = 0,
  raidTotal = 5,
  byKey = {},
}

do
  local byKey = ForsakenIODB.byKey
  local e

  e = {
    name = "Пивко",
    realmName = "Король-лич",
    realmSlug = "lich-king",
    class = "Друид",
    classFile = "DRUID",
    spec = "Сила зверя",
    specID = 103,
    score = 3298,
    rank = 1,
    color = "ff7a22",
    runs = 30,
    bestTier = 45,
    score20 = 475,
    score30 = 325,
    score35 = 220,
    score40 = 880,
    score45 = 1398,
    runs20 = 15,
    runs30 = 5,
    runs35 = 2,
    runs40 = 4,
    runs45 = 4,
    raidsCompleted = 3,
    bestDungeon = "Логово Нелтариона",
    bestDungeonEn = "Neltharion's Lair",
    bestDungeonZh = "奈萨里奥的巢穴",
    bestDungeonTier = 45,
    bestDungeonScore = 350,
    raidsTotal = 5,
    specs = {
      { role = "dps", spec = "Сила зверя", specID = 103, score = 3298 },
    },
  }
  byKey["пивко-lichking"] = e
  byKey["пивко-корольлич"] = e

  e = {
    name = "Эльрум",
    realmName = "Король-лич",
    realmSlug = "lich-king",
    class = "Друид",
    classFile = "DRUID",
    spec = "Сила зверя",
    specID = 103,
    score = 3294,
    rank = 2,
    color = "ff7825",
    runs = 30,
    bestTier = 45,
    score20 = 473,
    score30 = 325,
    score35 = 220,
    score40 = 880,
    score45 = 1396,
    runs20 = 15,
    runs30 = 5,
    runs35 = 2,
    runs40 = 4,
    runs45 = 4,
    raidsCompleted = 1,
    bestDungeon = "Чаща Темного Сердца",
    bestDungeonEn = "Darkheart Thicket",
    bestDungeonZh = "黑心林地",
    bestDungeonTier = 45,
    bestDungeonScore = 350,
    raidsTotal = 5,
    specs = {
      { role = "dps", spec = "Сила зверя", specID = 103, score = 3211 },
      { role = "healer", spec = "Исцеление", specID = 105, score = 65 },
      { role = "dps", spec = "Баланс", specID = 102, score = 18 },
    },
  }
  byKey["эльрум-lichking"] = e
  byKey["эльрум-корольлич"] = e

  e = {
    name = "Гт",
    realmName = "Борейская тундра",
    realmSlug = "borean-tundra",
    class = "Монах",
    classFile = "MONK",
    spec = "Танцующий с ветром",
    specID = 269,
    score = 3241,
    rank = 3,
    color = "ff732d",
    runs = 30,
    bestTier = 45,
    score20 = 425,
    score30 = 325,
    score35 = 219,
    score40 = 880,
    score45 = 1392,
    runs20 = 15,
    runs30 = 5,
    runs35 = 2,
    runs40 = 4,
    runs45 = 4,
    raidsCompleted = 3,
    bestDungeon = "Логово Нелтариона",
    bestDungeonEn = "Neltharion's Lair",
    bestDungeonZh = "奈萨里奥的巢穴",
    bestDungeonTier = 45,
    bestDungeonScore = 350,
    raidsTotal = 5,
    specs = {
      { role = "tank", spec = "Хмелевар", specID = 268, score = 3241 },
    },
  }
  byKey["гт-boreantundra"] = e
  byKey["гт-борейскаятундра"] = e

  e = {
    name = "Allarían",
    realmName = "Silvermoon",
    realmSlug = "silvermoon",
    class = "Монах",
    classFile = "MONK",
    spec = "Танцующий с ветром",
    specID = 269,
    score = 3188,
    rank = 4,
    color = "ff6d35",
    runs = 30,
    bestTier = 45,
    score20 = 393,
    score30 = 321,
    score35 = 216,
    score40 = 875,
    score45 = 1383,
    runs20 = 15,
    runs30 = 5,
    runs35 = 2,
    runs40 = 4,
    runs45 = 4,
    raidsCompleted = 3,
    bestDungeon = "Крепость Черной Ладьи",
    bestDungeonEn = "Black Rook Hold",
    bestDungeonZh = "黑鸦堡垒",
    bestDungeonTier = 45,
    bestDungeonScore = 350,
    raidsTotal = 5,
    specs = {
      { role = "tank", spec = "Хмелевар", specID = 268, score = 2533 },
      { role = "dps", spec = "Танцующий с ветром", specID = 269, score = 655 },
    },
  }
  byKey["allarían-silvermoon"] = e

  e = {
    name = "Сердцефармка",
    realmName = "Король-лич",
    realmSlug = "lich-king",
    class = "Воин",
    classFile = "WARRIOR",
    spec = "Защита",
    specID = 73,
    score = 3175,
    rank = 5,
    color = "ff6b39",
    runs = 30,
    bestTier = 45,
    score20 = 428,
    score30 = 314,
    score35 = 207,
    score40 = 855,
    score45 = 1371,
    runs20 = 15,
    runs30 = 5,
    runs35 = 2,
    runs40 = 4,
    runs45 = 4,
    raidsCompleted = 2,
    bestDungeon = "Логово Нелтариона",
    bestDungeonEn = "Neltharion's Lair",
    bestDungeonZh = "奈萨里奥的巢穴",
    bestDungeonTier = 45,
    bestDungeonScore = 348,
    raidsTotal = 5,
    specs = {
      { role = "tank", spec = "Защита", specID = 73, score = 3175 },
    },
  }
  byKey["сердцефармка-lichking"] = e
  byKey["сердцефармка-корольлич"] = e

  e = {
    name = "Кавочавоо",
    realmName = "Вечная Песня",
    realmSlug = "eversong",
    class = "Воин",
    classFile = "WARRIOR",
    spec = "Неистовство",
    specID = 72,
    score = 3088,
    rank = 6,
    color = "ff6345",
    runs = 30,
    bestTier = 45,
    score20 = 399,
    score30 = 321,
    score35 = 201,
    score40 = 856,
    score45 = 1311,
    runs20 = 15,
    runs30 = 5,
    runs35 = 2,
    runs40 = 4,
    runs45 = 4,
    raidsCompleted = 0,
    bestDungeon = "Крепость Черной Ладьи",
    bestDungeonEn = "Black Rook Hold",
    bestDungeonZh = "黑鸦堡垒",
    bestDungeonTier = 45,
    bestDungeonScore = 336,
    raidsTotal = 5,
    specs = {
      { role = "dps", spec = "Неистовство", specID = 72, score = 3088 },
    },
  }
  byKey["кавочавоо-eversong"] = e
  byKey["кавочавоо-вечнаяпесня"] = e

  e = {
    name = "Кронов",
    realmName = "Гордунни",
    realmSlug = "gordunni",
    class = "Жрец",
    classFile = "PRIEST",
    spec = "Свет",
    specID = 257,
    score = 3011,
    rank = 7,
    color = "ff5c50",
    runs = 29,
    bestTier = 45,
    score20 = 377,
    score30 = 240,
    score35 = 152,
    score40 = 866,
    score45 = 1376,
    runs20 = 15,
    runs30 = 4,
    runs35 = 2,
    runs40 = 4,
    runs45 = 4,
    raidsCompleted = 3,
    bestDungeon = "Логово Нелтариона",
    bestDungeonEn = "Neltharion's Lair",
    bestDungeonZh = "奈萨里奥的巢穴",
    bestDungeonTier = 45,
    bestDungeonScore = 350,
    raidsTotal = 5,
    specs = {
      { role = "healer", spec = "Свет", specID = 257, score = 2961 },
      { role = "dps", spec = "Тьма", specID = 258, score = 50 },
    },
  }
  byKey["кронов-gordunni"] = e
  byKey["кронов-гордунни"] = e

  e = {
    name = "Прега",
    realmName = "Свежеватель Душ",
    realmSlug = "soulflayer",
    class = "Воин",
    classFile = "WARRIOR",
    spec = "Оружие",
    specID = 71,
    score = 2970,
    rank = 8,
    color = "ff5756",
    runs = 26,
    bestTier = 45,
    score20 = 277,
    score30 = 249,
    score35 = 220,
    score40 = 874,
    score45 = 1350,
    runs20 = 12,
    runs30 = 4,
    runs35 = 2,
    runs40 = 4,
    runs45 = 4,
    raidsCompleted = 3,
    bestDungeon = "Halls of Valor",
    bestDungeonEn = "Halls of Valor",
    bestDungeonZh = nil,
    bestDungeonTier = 45,
    bestDungeonScore = 345,
    raidsTotal = 5,
    specs = {
      { role = "dps", spec = "Неистовство", specID = 72, score = 2970 },
    },
  }
  byKey["прега-soulflayer"] = e
  byKey["прега-свежевательдуш"] = e

  e = {
    name = "Yààx",
    realmName = "Ravencrest",
    realmSlug = "ravencrest",
    class = "Воин",
    classFile = "WARRIOR",
    spec = "Защита",
    specID = 73,
    score = 2885,
    rank = 9,
    color = "ff5062",
    runs = 21,
    bestTier = 45,
    score20 = 203,
    score30 = 325,
    score35 = 106,
    score40 = 864,
    score45 = 1387,
    runs20 = 7,
    runs30 = 5,
    runs35 = 1,
    runs40 = 4,
    runs45 = 4,
    raidsCompleted = 3,
    bestDungeon = "Чаща Темного Сердца",
    bestDungeonEn = "Darkheart Thicket",
    bestDungeonZh = "黑心林地",
    bestDungeonTier = 45,
    bestDungeonScore = 350,
    raidsTotal = 5,
    specs = {
      { role = "dps", spec = "Неистовство", specID = 72, score = 2885 },
    },
  }
  byKey["yààx-ravencrest"] = e

  e = {
    name = "Амнезия",
    realmName = "Азурегос",
    realmSlug = "azuregos",
    class = "Разбойник",
    classFile = "ROGUE",
    spec = "Ликвидация",
    specID = 259,
    score = 2826,
    rank = 10,
    color = "f94d71",
    runs = 22,
    bestTier = 45,
    score20 = 365,
    score30 = 128,
    score35 = 97,
    score40 = 871,
    score45 = 1365,
    runs20 = 11,
    runs30 = 2,
    runs35 = 1,
    runs40 = 4,
    runs45 = 4,
    raidsCompleted = 3,
    bestDungeon = "Крепость Черной Ладьи",
    bestDungeonEn = "Black Rook Hold",
    bestDungeonZh = "黑鸦堡垒",
    bestDungeonTier = 45,
    bestDungeonScore = 350,
    raidsTotal = 5,
    specs = {
      { role = "dps", spec = "Ликвидация", specID = 259, score = 2396 },
      { role = "dps", spec = "Головорез", specID = 260, score = 430 },
    },
  }
  byKey["амнезия-azuregos"] = e
  byKey["амнезия-азурегос"] = e

  e = {
    name = "Keotore",
    realmName = "Ravencrest",
    realmSlug = "ravencrest",
    class = "Паладин",
    classFile = "PALADIN",
    spec = "Свет",
    specID = 65,
    score = 2561,
    rank = 11,
    color = "df47a9",
    runs = 19,
    bestTier = 45,
    score20 = 193,
    score30 = 230,
    score35 = 109,
    score40 = 653,
    score45 = 1376,
    runs20 = 7,
    runs30 = 4,
    runs35 = 1,
    runs40 = 3,
    runs45 = 4,
    raidsCompleted = 2,
    bestDungeon = "Логово Нелтариона",
    bestDungeonEn = "Neltharion's Lair",
    bestDungeonZh = "奈萨里奥的巢穴",
    bestDungeonTier = 45,
    bestDungeonScore = 348,
    raidsTotal = 5,
    specs = {
      { role = "healer", spec = "Свет", specID = 65, score = 2368 },
      { role = "dps", spec = "Воздаяние", specID = 70, score = 109 },
      { role = "tank", spec = "Защита", specID = 66, score = 84 },
    },
  }
  byKey["keotore-ravencrest"] = e

  e = {
    name = "Фаённа",
    realmName = "Вечная Песня",
    realmSlug = "eversong",
    class = "Жрец",
    classFile = "PRIEST",
    spec = "Послушание",
    specID = 256,
    score = 2558,
    rank = 12,
    color = "dd46ae",
    runs = 17,
    bestTier = 45,
    score20 = 48,
    score30 = 301,
    score35 = 194,
    score40 = 841,
    score45 = 1174,
    runs20 = 2,
    runs30 = 5,
    runs35 = 2,
    runs40 = 4,
    runs45 = 4,
    raidsCompleted = 2,
    bestDungeon = "Halls of Valor",
    bestDungeonEn = "Halls of Valor",
    bestDungeonZh = nil,
    bestDungeonTier = 45,
    bestDungeonScore = 329,
    raidsTotal = 5,
    specs = {
      { role = "healer", spec = "Послушание", specID = 256, score = 2558 },
    },
  }
  byKey["фаённа-eversong"] = e
  byKey["фаённа-вечнаяпесня"] = e

  e = {
    name = "Ббелыйрыцарь",
    realmName = "Седогрив",
    realmSlug = "greymane",
    class = "Паладин",
    classFile = "PALADIN",
    spec = "Защита",
    specID = 66,
    score = 2520,
    rank = 13,
    color = "d844b9",
    runs = 15,
    bestTier = 45,
    score20 = 0,
    score30 = 280,
    score35 = 201,
    score40 = 861,
    score45 = 1178,
    runs20 = 0,
    runs30 = 5,
    runs35 = 2,
    runs40 = 4,
    runs45 = 4,
    raidsCompleted = 5,
    bestDungeon = "Halls of Valor",
    bestDungeonEn = "Halls of Valor",
    bestDungeonZh = nil,
    bestDungeonTier = 45,
    bestDungeonScore = 329,
    raidsTotal = 5,
    specs = {
      { role = "tank", spec = "Защита", specID = 66, score = 2312 },
      { role = "dps", spec = "Воздаяние", specID = 70, score = 208 },
    },
  }
  byKey["ббелыйрыцарь-greymane"] = e
  byKey["ббелыйрыцарь-седогрив"] = e

  e = {
    name = "Bezdna",
    realmName = "Dentarg",
    realmSlug = "dentarg",
    class = "Жрец",
    classFile = "PRIEST",
    spec = "Свет",
    specID = 257,
    score = 2390,
    rank = 14,
    color = "ca41d7",
    runs = 13,
    bestTier = 45,
    score20 = 50,
    score30 = 195,
    score35 = 110,
    score40 = 654,
    score45 = 1381,
    runs20 = 2,
    runs30 = 3,
    runs35 = 1,
    runs40 = 3,
    runs45 = 4,
    raidsCompleted = 1,
    bestDungeon = "Крепость Черной Ладьи",
    bestDungeonEn = "Black Rook Hold",
    bestDungeonZh = "黑鸦堡垒",
    bestDungeonTier = 45,
    bestDungeonScore = 350,
    raidsTotal = 5,
    specs = {
      { role = "healer", spec = "Послушание", specID = 256, score = 2340 },
      { role = "healer", spec = "Свет", specID = 257, score = 50 },
    },
  }
  byKey["bezdna-dentarg"] = e

  e = {
    name = "Izum",
    realmName = "Ravencrest",
    realmSlug = "ravencrest",
    class = "Разбойник",
    classFile = "ROGUE",
    spec = "Головорез",
    specID = 260,
    score = 2169,
    rank = 15,
    color = "b13fff",
    runs = 12,
    bestTier = 45,
    score20 = 48,
    score30 = 82,
    score35 = 214,
    score40 = 437,
    score45 = 1388,
    runs20 = 2,
    runs30 = 2,
    runs35 = 2,
    runs40 = 2,
    runs45 = 4,
    raidsCompleted = 3,
    bestDungeon = "Логово Нелтариона",
    bestDungeonEn = "Neltharion's Lair",
    bestDungeonZh = "奈萨里奥的巢穴",
    bestDungeonTier = 45,
    bestDungeonScore = 350,
    raidsTotal = 5,
    specs = {
      { role = "dps", spec = "Ликвидация", specID = 259, score = 2121 },
      { role = "dps", spec = "Головорез", specID = 260, score = 48 },
    },
  }
  byKey["izum-ravencrest"] = e

  e = {
    name = "Бездонная",
    realmName = "Азурегос",
    realmSlug = "azuregos",
    class = "Воин",
    classFile = "WARRIOR",
    spec = "Неистовство",
    specID = 72,
    score = 2004,
    rank = 16,
    color = "8e4fff",
    runs = 26,
    bestTier = 45,
    score20 = 405,
    score30 = 247,
    score35 = 156,
    score40 = 853,
    score45 = 343,
    runs20 = 15,
    runs30 = 4,
    runs35 = 2,
    runs40 = 4,
    runs45 = 1,
    raidsCompleted = 2,
    bestDungeon = "Чаща Темного Сердца",
    bestDungeonEn = "Darkheart Thicket",
    bestDungeonZh = "黑心林地",
    bestDungeonTier = 45,
    bestDungeonScore = 343,
    raidsTotal = 5,
    specs = {
      { role = "dps", spec = "Неистовство", specID = 72, score = 2004 },
    },
  }
  byKey["бездонная-azuregos"] = e
  byKey["бездонная-азурегос"] = e

  e = {
    name = "Харфорд",
    realmName = "Азурегос",
    realmSlug = "azuregos",
    class = "Охотник",
    classFile = "HUNTER",
    spec = "Выживание",
    specID = 255,
    score = 1972,
    rank = 17,
    color = "8454ff",
    runs = 12,
    bestTier = 45,
    score20 = 0,
    score30 = 275,
    score35 = 219,
    score40 = 433,
    score45 = 1045,
    runs20 = 0,
    runs30 = 5,
    runs35 = 2,
    runs40 = 2,
    runs45 = 3,
    raidsCompleted = 3,
    bestDungeon = "Логово Нелтариона",
    bestDungeonEn = "Neltharion's Lair",
    bestDungeonZh = "奈萨里奥的巢穴",
    bestDungeonTier = 45,
    bestDungeonScore = 350,
    raidsTotal = 5,
    specs = {
      { role = "dps", spec = "Стрельба", specID = 254, score = 1972 },
    },
  }
  byKey["харфорд-azuregos"] = e
  byKey["харфорд-азурегос"] = e

  e = {
    name = "Чугунплита",
    realmName = "Гордунни",
    realmSlug = "gordunni",
    class = "Монах",
    classFile = "MONK",
    spec = "Хмелевар",
    specID = 268,
    score = 1741,
    rank = 18,
    color = "546aff",
    runs = 7,
    bestTier = 45,
    score20 = 0,
    score30 = 60,
    score35 = 0,
    score40 = 646,
    score45 = 1035,
    runs20 = 0,
    runs30 = 1,
    runs35 = 0,
    runs40 = 3,
    runs45 = 3,
    raidsCompleted = 2,
    bestDungeon = "Halls of Valor",
    bestDungeonEn = "Halls of Valor",
    bestDungeonZh = nil,
    bestDungeonTier = 45,
    bestDungeonScore = 348,
    raidsTotal = 5,
    specs = {
      { role = "tank", spec = "Хмелевар", specID = 268, score = 1741 },
    },
  }
  byKey["чугунплита-gordunni"] = e
  byKey["чугунплита-гордунни"] = e

  e = {
    name = "Шевронщица",
    realmName = "Вечная Песня",
    realmSlug = "eversong",
    class = "Разбойник",
    classFile = "ROGUE",
    spec = "Ликвидация",
    specID = 259,
    score = 1464,
    rank = 19,
    color = "1b85ff",
    runs = 15,
    bestTier = 45,
    score20 = 143,
    score30 = 305,
    score35 = 208,
    score40 = 196,
    score45 = 612,
    runs20 = 5,
    runs30 = 5,
    runs35 = 2,
    runs40 = 1,
    runs45 = 2,
    raidsCompleted = 1,
    bestDungeon = "Чаща Темного Сердца",
    bestDungeonEn = "Darkheart Thicket",
    bestDungeonZh = "黑心林地",
    bestDungeonTier = 45,
    bestDungeonScore = 331,
    raidsTotal = 5,
    specs = {
      { role = "dps", spec = "Ликвидация", specID = 259, score = 1369 },
      { role = "dps", spec = "Головорез", specID = 260, score = 95 },
    },
  }
  byKey["шевронщица-eversong"] = e
  byKey["шевронщица-вечнаяпесня"] = e

  e = {
    name = "Юша",
    realmName = "Король-лич",
    realmSlug = "lich-king",
    class = "Воин",
    classFile = "WARRIOR",
    spec = "Неистовство",
    specID = 72,
    score = 1393,
    rank = 20,
    color = "188bfb",
    runs = 13,
    bestTier = 45,
    score20 = 225,
    score30 = 60,
    score35 = 0,
    score40 = 431,
    score45 = 677,
    runs20 = 8,
    runs30 = 1,
    runs35 = 0,
    runs40 = 2,
    runs45 = 2,
    raidsCompleted = 1,
    bestDungeon = "Чаща Темного Сердца",
    bestDungeonEn = "Darkheart Thicket",
    bestDungeonZh = "黑心林地",
    bestDungeonTier = 45,
    bestDungeonScore = 345,
    raidsTotal = 5,
    specs = {
      { role = "dps", spec = "Неистовство", specID = 72, score = 1393 },
    },
  }
  byKey["юша-lichking"] = e
  byKey["юша-корольлич"] = e

  e = {
    name = "Allaríán",
    realmName = "Silvermoon",
    realmSlug = "silvermoon",
    class = "Шаман",
    classFile = "SHAMAN",
    spec = "Исцеление",
    specID = 264,
    score = 1362,
    rank = 21,
    color = "1a8ff8",
    runs = 12,
    bestTier = 45,
    score20 = 48,
    score30 = 305,
    score35 = 219,
    score40 = 440,
    score45 = 350,
    runs20 = 2,
    runs30 = 5,
    runs35 = 2,
    runs40 = 2,
    runs45 = 1,
    raidsCompleted = 0,
    bestDungeon = "Чаща Темного Сердца",
    bestDungeonEn = "Darkheart Thicket",
    bestDungeonZh = "黑心林地",
    bestDungeonTier = 45,
    bestDungeonScore = 350,
    raidsTotal = 5,
    specs = {
      { role = "healer", spec = "Исцеление", specID = 264, score = 1362 },
    },
  }
  byKey["allaríán-silvermoon"] = e

  e = {
    name = "Pharisee",
    realmName = "Ravencrest",
    realmSlug = "ravencrest",
    class = "Монах",
    classFile = "MONK",
    spec = "Танцующий с ветром",
    specID = 269,
    score = 1305,
    rank = 22,
    color = "1c94f4",
    runs = 21,
    bestTier = 45,
    score20 = 413,
    score30 = 143,
    score35 = 110,
    score40 = 0,
    score45 = 639,
    runs20 = 15,
    runs30 = 3,
    runs35 = 1,
    runs40 = 0,
    runs45 = 2,
    raidsCompleted = 2,
    bestDungeon = "Чаща Темного Сердца",
    bestDungeonEn = "Darkheart Thicket",
    bestDungeonZh = "黑心林地",
    bestDungeonTier = 45,
    bestDungeonScore = 342,
    raidsTotal = 5,
    specs = {
      { role = "healer", spec = "Ткач туманов", specID = 270, score = 1305 },
    },
  }
  byKey["pharisee-ravencrest"] = e

  e = {
    name = "Qraki",
    realmName = "Kazzak",
    realmSlug = "kazzak",
    class = "Друид",
    classFile = "DRUID",
    spec = "Исцеление",
    specID = 105,
    score = 1230,
    rank = 23,
    color = "209bee",
    runs = 14,
    bestTier = 45,
    score20 = 315,
    score30 = 65,
    score35 = 97,
    score40 = 432,
    score45 = 321,
    runs20 = 9,
    runs30 = 1,
    runs35 = 1,
    runs40 = 2,
    runs45 = 1,
    raidsCompleted = 1,
    bestDungeon = "Логово Нелтариона",
    bestDungeonEn = "Neltharion's Lair",
    bestDungeonZh = "奈萨里奥的巢穴",
    bestDungeonTier = 45,
    bestDungeonScore = 321,
    raidsTotal = 5,
    specs = {
      { role = "healer", spec = "Исцеление", specID = 105, score = 950 },
      { role = "dps", spec = "Баланс", specID = 102, score = 280 },
    },
  }
  byKey["qraki-kazzak"] = e

  e = {
    name = "Luckyou",
    realmName = "Aggramar",
    realmSlug = "aggramar",
    class = "Паладин",
    classFile = "PALADIN",
    spec = "Защита",
    specID = 66,
    score = 1187,
    rank = 24,
    color = "229fea",
    runs = 6,
    bestTier = 45,
    score20 = 20,
    score30 = 0,
    score35 = 0,
    score40 = 854,
    score45 = 313,
    runs20 = 1,
    runs30 = 0,
    runs35 = 0,
    runs40 = 4,
    runs45 = 1,
    raidsCompleted = 1,
    bestDungeon = "Логово Нелтариона",
    bestDungeonEn = "Neltharion's Lair",
    bestDungeonZh = "奈萨里奥的巢穴",
    bestDungeonTier = 45,
    bestDungeonScore = 313,
    raidsTotal = 5,
    specs = {
      { role = "dps", spec = "Воздаяние", specID = 70, score = 1187 },
    },
  }
  byKey["luckyou-aggramar"] = e

  e = {
    name = "Пойндэкстер",
    realmName = "Свежеватель Душ",
    realmSlug = "soulflayer",
    class = "Шаман",
    classFile = "SHAMAN",
    spec = "Совершенствование",
    specID = 263,
    score = 1158,
    rank = 25,
    color = "23a2e7",
    runs = 18,
    bestTier = 40,
    score20 = 273,
    score30 = 241,
    score35 = 207,
    score40 = 437,
    score45 = 0,
    runs20 = 10,
    runs30 = 4,
    runs35 = 2,
    runs40 = 2,
    runs45 = 0,
    raidsCompleted = 3,
    bestDungeon = "Шлаковые шахты Кровавого Молота",
    bestDungeonEn = "Bloodmaul Slag Mines",
    bestDungeonZh = "血槌炉渣矿井",
    bestDungeonTier = 40,
    bestDungeonScore = 220,
    raidsTotal = 5,
    specs = {
      { role = "dps", spec = "Совершенствование", specID = 263, score = 1158 },
    },
  }
  byKey["пойндэкстер-soulflayer"] = e
  byKey["пойндэкстер-свежевательдуш"] = e

  e = {
    name = "Нтс",
    realmName = "Борейская тундра",
    realmSlug = "borean-tundra",
    class = "Шаман",
    classFile = "SHAMAN",
    spec = "Исцеление",
    specID = 264,
    score = 1097,
    rank = 26,
    color = "26a8e2",
    runs = 5,
    bestTier = 45,
    score20 = 18,
    score30 = 0,
    score35 = 0,
    score40 = 426,
    score45 = 653,
    runs20 = 1,
    runs30 = 0,
    runs35 = 0,
    runs40 = 2,
    runs45 = 2,
    raidsCompleted = 0,
    bestDungeon = "Чаща Темного Сердца",
    bestDungeonEn = "Darkheart Thicket",
    bestDungeonZh = "黑心林地",
    bestDungeonTier = 45,
    bestDungeonScore = 340,
    raidsTotal = 5,
    specs = {
      { role = "healer", spec = "Исцеление", specID = 264, score = 1097 },
    },
  }
  byKey["нтс-boreantundra"] = e
  byKey["нтс-борейскаятундра"] = e

  e = {
    name = "Синвоин",
    realmName = "Гордунни",
    realmSlug = "gordunni",
    class = "Воин",
    classFile = "WARRIOR",
    spec = "Неистовство",
    specID = 72,
    score = 887,
    rank = 27,
    color = "2eb7d5",
    runs = 15,
    bestTier = 40,
    score20 = 234,
    score30 = 182,
    score35 = 46,
    score40 = 425,
    score45 = 0,
    runs20 = 9,
    runs30 = 3,
    runs35 = 1,
    runs40 = 2,
    runs45 = 0,
    raidsCompleted = 1,
    bestDungeon = "Upper Blackrock Spire",
    bestDungeonEn = "Upper Blackrock Spire",
    bestDungeonZh = nil,
    bestDungeonTier = 40,
    bestDungeonScore = 215,
    raidsTotal = 5,
    specs = {
      { role = "dps", spec = "Неистовство", specID = 72, score = 887 },
    },
  }
  byKey["синвоин-gordunni"] = e
  byKey["синвоин-гордунни"] = e

  e = {
    name = "Ускериа",
    realmName = "Гордунни",
    realmSlug = "gordunni",
    class = "Охотник",
    classFile = "HUNTER",
    spec = "Стрельба",
    specID = 254,
    score = 794,
    rank = 28,
    color = "31bfce",
    runs = 9,
    bestTier = 45,
    score20 = 134,
    score30 = 63,
    score35 = 46,
    score40 = 220,
    score45 = 331,
    runs20 = 5,
    runs30 = 1,
    runs35 = 1,
    runs40 = 1,
    runs45 = 1,
    raidsCompleted = 0,
    bestDungeon = "Halls of Valor",
    bestDungeonEn = "Halls of Valor",
    bestDungeonZh = nil,
    bestDungeonTier = 45,
    bestDungeonScore = 331,
    raidsTotal = 5,
    specs = {
      { role = "dps", spec = "Повелитель зверей", specID = 253, score = 331 },
      { role = "dps", spec = "Стрельба", specID = 254, score = 266 },
      { role = "dps", spec = "Выживание", specID = 255, score = 197 },
    },
  }
  byKey["ускериа-gordunni"] = e
  byKey["ускериа-гордунни"] = e

  e = {
    name = "Рэдриор",
    realmName = "Свежеватель Душ",
    realmSlug = "soulflayer",
    class = "Рыцарь смерти",
    classFile = "DEATHKNIGHT",
    spec = "Нечестивость",
    specID = 252,
    score = 776,
    rank = 29,
    color = "33c1cc",
    runs = 5,
    bestTier = 45,
    score20 = 0,
    score30 = 171,
    score35 = 0,
    score40 = 0,
    score45 = 605,
    runs20 = 0,
    runs30 = 3,
    runs35 = 0,
    runs40 = 0,
    runs45 = 2,
    raidsCompleted = 3,
    bestDungeon = "Крепость Черной Ладьи",
    bestDungeonEn = "Black Rook Hold",
    bestDungeonZh = "黑鸦堡垒",
    bestDungeonTier = 45,
    bestDungeonScore = 311,
    raidsTotal = 5,
    specs = {
      { role = "dps", spec = "Нечестивость", specID = 252, score = 776 },
    },
  }
  byKey["рэдриор-soulflayer"] = e
  byKey["рэдриор-свежевательдуш"] = e

  e = {
    name = "Рекзеп",
    realmName = "Вечная Песня",
    realmSlug = "eversong",
    class = "Жрец",
    classFile = "PRIEST",
    spec = "Тьма",
    specID = 258,
    score = 706,
    rank = 30,
    color = "35c6c5",
    runs = 6,
    bestTier = 45,
    score20 = 58,
    score30 = 0,
    score35 = 97,
    score40 = 215,
    score45 = 336,
    runs20 = 3,
    runs30 = 0,
    runs35 = 1,
    runs40 = 1,
    runs45 = 1,
    raidsCompleted = 2,
    bestDungeon = "Halls of Valor",
    bestDungeonEn = "Halls of Valor",
    bestDungeonZh = nil,
    bestDungeonTier = 45,
    bestDungeonScore = 336,
    raidsTotal = 5,
    specs = {
      { role = "healer", spec = "Послушание", specID = 256, score = 706 },
    },
  }
  byKey["рекзеп-eversong"] = e
  byKey["рекзеп-вечнаяпесня"] = e

  e = {
    name = "Рилмужик",
    realmName = "Вечная Песня",
    realmSlug = "eversong",
    class = "Шаман",
    classFile = "SHAMAN",
    spec = "Совершенствование",
    specID = 263,
    score = 656,
    rank = 31,
    color = "34c8bc",
    runs = 3,
    bestTier = 40,
    score20 = 0,
    score30 = 0,
    score35 = 0,
    score40 = 656,
    score45 = 0,
    runs20 = 0,
    runs30 = 0,
    runs35 = 0,
    runs40 = 3,
    runs45 = 0,
    raidsCompleted = 1,
    bestDungeon = "Железные доки",
    bestDungeonEn = "Iron Docks",
    bestDungeonZh = "钢铁码头",
    bestDungeonTier = 40,
    bestDungeonScore = 220,
    raidsTotal = 5,
    specs = {
      { role = "healer", spec = "Исцеление", specID = 264, score = 656 },
    },
  }
  byKey["рилмужик-eversong"] = e
  byKey["рилмужик-вечнаяпесня"] = e

  e = {
    name = "Yaxcs",
    realmName = "Ravencrest",
    realmSlug = "ravencrest",
    class = "Охотник",
    classFile = "HUNTER",
    spec = "Повелитель зверей",
    specID = 253,
    score = 533,
    rank = 32,
    color = "34cbab",
    runs = 2,
    bestTier = 45,
    score20 = 0,
    score30 = 0,
    score35 = 0,
    score40 = 220,
    score45 = 313,
    runs20 = 0,
    runs30 = 0,
    runs35 = 0,
    runs40 = 1,
    runs45 = 1,
    raidsCompleted = 1,
    bestDungeon = "Логово Нелтариона",
    bestDungeonEn = "Neltharion's Lair",
    bestDungeonZh = "奈萨里奥的巢穴",
    bestDungeonTier = 45,
    bestDungeonScore = 313,
    raidsTotal = 5,
    specs = {
      { role = "dps", spec = "Стрельба", specID = 254, score = 533 },
    },
  }
  byKey["yaxcs-ravencrest"] = e

  e = {
    name = "Дедуля",
    realmName = "Разувий",
    realmSlug = "razuvious",
    class = "Воин",
    classFile = "WARRIOR",
    spec = "Неистовство",
    specID = 72,
    score = 452,
    rank = 33,
    color = "33cd9e",
    runs = 3,
    bestTier = 45,
    score20 = 0,
    score30 = 65,
    score35 = 91,
    score40 = 0,
    score45 = 296,
    runs20 = 0,
    runs30 = 1,
    runs35 = 1,
    runs40 = 0,
    runs45 = 1,
    raidsCompleted = 3,
    bestDungeon = "Крепость Черной Ладьи",
    bestDungeonEn = "Black Rook Hold",
    bestDungeonZh = "黑鸦堡垒",
    bestDungeonTier = 45,
    bestDungeonScore = 296,
    raidsTotal = 5,
    specs = {
      { role = "dps", spec = "Неистовство", specID = 72, score = 452 },
    },
  }
  byKey["дедуля-razuvious"] = e
  byKey["дедуля-разувий"] = e

  e = {
    name = "Щедруля",
    realmName = "Вечная Песня",
    realmSlug = "eversong",
    class = "Охотник",
    classFile = "HUNTER",
    spec = "Выживание",
    specID = 255,
    score = 425,
    rank = 34,
    color = "33ce98",
    runs = 2,
    bestTier = 40,
    score20 = 0,
    score30 = 0,
    score35 = 0,
    score40 = 425,
    score45 = 0,
    runs20 = 0,
    runs30 = 0,
    runs35 = 0,
    runs40 = 2,
    runs45 = 0,
    raidsCompleted = 0,
    bestDungeon = "Upper Blackrock Spire",
    bestDungeonEn = "Upper Blackrock Spire",
    bestDungeonZh = nil,
    bestDungeonTier = 40,
    bestDungeonScore = 215,
    raidsTotal = 5,
    specs = {
      { role = "dps", spec = "Выживание", specID = 255, score = 215 },
      { role = "dps", spec = "Стрельба", specID = 254, score = 210 },
    },
  }
  byKey["щедруля-eversong"] = e
  byKey["щедруля-вечнаяпесня"] = e

  e = {
    name = "Geniy",
    realmName = "Kazzak",
    realmSlug = "kazzak",
    class = "Воин",
    classFile = "WARRIOR",
    spec = "Защита",
    specID = 73,
    score = 361,
    rank = 35,
    color = "32d08e",
    runs = 2,
    bestTier = 45,
    score20 = 0,
    score30 = 64,
    score35 = 0,
    score40 = 0,
    score45 = 297,
    runs20 = 0,
    runs30 = 1,
    runs35 = 0,
    runs40 = 0,
    runs45 = 1,
    raidsCompleted = 0,
    bestDungeon = "Halls of Valor",
    bestDungeonEn = "Halls of Valor",
    bestDungeonZh = nil,
    bestDungeonTier = 45,
    bestDungeonScore = 297,
    raidsTotal = 5,
    specs = {
      { role = "tank", spec = "Защита", specID = 73, score = 361 },
    },
  }
  byKey["geniy-kazzak"] = e

  e = {
    name = "Дриктас",
    realmName = "Король-лич",
    realmSlug = "lich-king",
    class = "Разбойник",
    classFile = "ROGUE",
    spec = "Головорез",
    specID = 260,
    score = 297,
    rank = 36,
    color = "32d283",
    runs = 1,
    bestTier = 45,
    score20 = 0,
    score30 = 0,
    score35 = 0,
    score40 = 0,
    score45 = 297,
    runs20 = 0,
    runs30 = 0,
    runs35 = 0,
    runs40 = 0,
    runs45 = 1,
    raidsCompleted = 3,
    bestDungeon = "Halls of Valor",
    bestDungeonEn = "Halls of Valor",
    bestDungeonZh = nil,
    bestDungeonTier = 45,
    bestDungeonScore = 297,
    raidsTotal = 5,
    specs = {
      { role = "dps", spec = "Ликвидация", specID = 259, score = 297 },
    },
  }
  byKey["дриктас-lichking"] = e
  byKey["дриктас-корольлич"] = e

  e = {
    name = "Охренителен",
    realmName = "Король-лич",
    realmSlug = "lich-king",
    class = "Паладин",
    classFile = "PALADIN",
    spec = "Воздаяние",
    specID = 70,
    score = 297,
    rank = 37,
    color = "32d280",
    runs = 1,
    bestTier = 45,
    score20 = 0,
    score30 = 0,
    score35 = 0,
    score40 = 0,
    score45 = 297,
    runs20 = 0,
    runs30 = 0,
    runs35 = 0,
    runs40 = 0,
    runs45 = 1,
    raidsCompleted = 2,
    bestDungeon = "Halls of Valor",
    bestDungeonEn = "Halls of Valor",
    bestDungeonZh = nil,
    bestDungeonTier = 45,
    bestDungeonScore = 297,
    raidsTotal = 5,
    specs = {
      { role = "dps", spec = "Воздаяние", specID = 70, score = 297 },
    },
  }
  byKey["охренителен-lichking"] = e
  byKey["охренителен-корольлич"] = e

  e = {
    name = "Экклесиаст",
    realmName = "Голдринн",
    realmSlug = "goldrinn",
    class = "Разбойник",
    classFile = "ROGUE",
    spec = "Ликвидация",
    specID = 259,
    score = 275,
    rank = 38,
    color = "31d37b",
    runs = 5,
    bestTier = 30,
    score20 = 0,
    score30 = 275,
    score35 = 0,
    score40 = 0,
    score45 = 0,
    runs20 = 0,
    runs30 = 5,
    runs35 = 0,
    runs40 = 0,
    runs45 = 0,
    raidsCompleted = 1,
    bestDungeon = "Кузня Душ",
    bestDungeonEn = "The Forge of Souls",
    bestDungeonZh = "灵魂熔炉",
    bestDungeonTier = 30,
    bestDungeonScore = 65,
    raidsTotal = 5,
    specs = {
      { role = "dps", spec = "Ликвидация", specID = 259, score = 275 },
    },
  }
  byKey["экклесиаст-goldrinn"] = e
  byKey["экклесиаст-голдринн"] = e

  e = {
    name = "Kuq",
    realmName = "Ravencrest",
    realmSlug = "ravencrest",
    class = "Воин",
    classFile = "WARRIOR",
    spec = "Защита",
    specID = 73,
    score = 274,
    rank = 39,
    color = "31d478",
    runs = 1,
    bestTier = 45,
    score20 = 0,
    score30 = 0,
    score35 = 0,
    score40 = 0,
    score45 = 274,
    runs20 = 0,
    runs30 = 0,
    runs35 = 0,
    runs40 = 0,
    runs45 = 1,
    raidsCompleted = 0,
    bestDungeon = "Крепость Черной Ладьи",
    bestDungeonEn = "Black Rook Hold",
    bestDungeonZh = "黑鸦堡垒",
    bestDungeonTier = 45,
    bestDungeonScore = 274,
    raidsTotal = 5,
    specs = {
      { role = "dps", spec = "Неистовство", specID = 72, score = 274 },
    },
  }
  byKey["kuq-ravencrest"] = e

  e = {
    name = "Дестрекс",
    realmName = "Свежеватель Душ",
    realmSlug = "soulflayer",
    class = "Воин",
    classFile = "WARRIOR",
    spec = "Неистовство",
    specID = 72,
    score = 243,
    rank = 40,
    color = "31d571",
    runs = 9,
    bestTier = 20,
    score20 = 243,
    score30 = 0,
    score35 = 0,
    score40 = 0,
    score45 = 0,
    runs20 = 9,
    runs30 = 0,
    runs35 = 0,
    runs40 = 0,
    runs45 = 0,
    raidsCompleted = 0,
    bestDungeon = "Кузня Душ",
    bestDungeonEn = "The Forge of Souls",
    bestDungeonZh = "灵魂熔炉",
    bestDungeonTier = 20,
    bestDungeonScore = 35,
    raidsTotal = 5,
    specs = {
      { role = "dps", spec = "Неистовство", specID = 72, score = 243 },
    },
  }
  byKey["дестрекс-soulflayer"] = e
  byKey["дестрекс-свежевательдуш"] = e

  e = {
    name = "Каспий",
    realmName = "Разувий",
    realmSlug = "razuvious",
    class = "Друид",
    classFile = "DRUID",
    spec = "Сила зверя",
    specID = 103,
    score = 240,
    rank = 41,
    color = "31d66e",
    runs = 1,
    bestTier = 45,
    score20 = 0,
    score30 = 0,
    score35 = 0,
    score40 = 0,
    score45 = 240,
    runs20 = 0,
    runs30 = 0,
    runs35 = 0,
    runs40 = 0,
    runs45 = 1,
    raidsCompleted = 2,
    bestDungeon = "Чаща Темного Сердца",
    bestDungeonEn = "Darkheart Thicket",
    bestDungeonZh = "黑心林地",
    bestDungeonTier = 45,
    bestDungeonScore = 240,
    raidsTotal = 5,
    specs = {
      { role = "dps", spec = "Сила зверя", specID = 103, score = 240 },
    },
  }
  byKey["каспий-razuvious"] = e
  byKey["каспий-разувий"] = e

  e = {
    name = "Разка",
    realmName = "Борейская тундра",
    realmSlug = "borean-tundra",
    class = "Паладин",
    classFile = "PALADIN",
    spec = "Защита",
    specID = 66,
    score = 215,
    rank = 42,
    color = "31d768",
    runs = 1,
    bestTier = 40,
    score20 = 0,
    score30 = 0,
    score35 = 0,
    score40 = 215,
    score45 = 0,
    runs20 = 0,
    runs30 = 0,
    runs35 = 0,
    runs40 = 1,
    runs45 = 0,
    raidsCompleted = 0,
    bestDungeon = "Железные доки",
    bestDungeonEn = "Iron Docks",
    bestDungeonZh = "钢铁码头",
    bestDungeonTier = 40,
    bestDungeonScore = 215,
    raidsTotal = 5,
    specs = {
      { role = "tank", spec = "Защита", specID = 66, score = 215 },
    },
  }
  byKey["разка-boreantundra"] = e
  byKey["разка-борейскаятундра"] = e

  e = {
    name = "Гд",
    realmName = "Борейская тундра",
    realmSlug = "borean-tundra",
    class = "Охотник на демонов",
    classFile = "DEMONHUNTER",
    spec = "Месть",
    specID = 581,
    score = 110,
    rank = 43,
    color = "32d95b",
    runs = 1,
    bestTier = 35,
    score20 = 0,
    score30 = 0,
    score35 = 110,
    score40 = 0,
    score45 = 0,
    runs20 = 0,
    runs30 = 0,
    runs35 = 1,
    runs40 = 0,
    runs45 = 0,
    raidsCompleted = 3,
    bestDungeon = "Храм Нефритовой Змеи",
    bestDungeonEn = "Temple of the Jade Serpent",
    bestDungeonZh = "青龙寺",
    bestDungeonTier = 35,
    bestDungeonScore = 110,
    raidsTotal = 5,
    specs = {
      { role = "tank", spec = "Месть", specID = 581, score = 110 },
    },
  }
  byKey["гд-boreantundra"] = e
  byKey["гд-борейскаятундра"] = e

  e = {
    name = "Артазий",
    realmName = "Гордунни",
    realmSlug = "gordunni",
    class = "Воин",
    classFile = "WARRIOR",
    spec = "Неистовство",
    specID = 72,
    score = 99,
    rank = 44,
    color = "39da61",
    runs = 2,
    bestTier = 30,
    score20 = 0,
    score30 = 99,
    score35 = 0,
    score40 = 0,
    score45 = 0,
    runs20 = 0,
    runs30 = 2,
    runs35 = 0,
    runs40 = 0,
    runs45 = 0,
    raidsCompleted = 1,
    bestDungeon = "Чертоги Молний",
    bestDungeonEn = "Halls of Lightning",
    bestDungeonZh = "闪电大厅",
    bestDungeonTier = 30,
    bestDungeonScore = 51,
    raidsTotal = 5,
    specs = {
      { role = "dps", spec = "Неистовство", specID = 72, score = 99 },
    },
  }
  byKey["артазий-gordunni"] = e
  byKey["артазий-гордунни"] = e

  e = {
    name = "Иснупсен",
    realmName = "Галакронд",
    realmSlug = "galakrond",
    class = "Разбойник",
    classFile = "ROGUE",
    spec = "Ликвидация",
    specID = 259,
    score = 59,
    rank = 45,
    color = "47dc6c",
    runs = 3,
    bestTier = 20,
    score20 = 59,
    score30 = 0,
    score35 = 0,
    score40 = 0,
    score45 = 0,
    runs20 = 3,
    runs30 = 0,
    runs35 = 0,
    runs40 = 0,
    runs45 = 0,
    raidsCompleted = 0,
    bestDungeon = "Шлаковые шахты Кровавого Молота",
    bestDungeonEn = "Bloodmaul Slag Mines",
    bestDungeonZh = "血槌炉渣矿井",
    bestDungeonTier = 20,
    bestDungeonScore = 20,
    raidsTotal = 5,
    specs = {
      { role = "dps", spec = "Ликвидация", specID = 259, score = 59 },
    },
  }
  byKey["иснупсен-galakrond"] = e
  byKey["иснупсен-галакронд"] = e

  e = {
    name = "Сейв",
    realmName = "Гром",
    realmSlug = "grom",
    class = "Друид",
    classFile = "DRUID",
    spec = "Страж",
    specID = 104,
    score = 20,
    rank = 46,
    color = "54de77",
    runs = 1,
    bestTier = 20,
    score20 = 20,
    score30 = 0,
    score35 = 0,
    score40 = 0,
    score45 = 0,
    runs20 = 1,
    runs30 = 0,
    runs35 = 0,
    runs40 = 0,
    runs45 = 0,
    raidsCompleted = 0,
    bestDungeon = "Halls of Stone",
    bestDungeonEn = "Halls of Stone",
    bestDungeonZh = nil,
    bestDungeonTier = 20,
    bestDungeonScore = 20,
    raidsTotal = 5,
    specs = {
      { role = "tank", spec = "Страж", specID = 104, score = 20 },
    },
  }
  byKey["сейв-grom"] = e
  byKey["сейв-гром"] = e

  e = {
    name = "Фростмагх",
    realmName = "Вечная Песня",
    realmSlug = "eversong",
    class = "Рыцарь смерти",
    classFile = "DEATHKNIGHT",
    spec = "Нечестивость",
    specID = 252,
    score = 19,
    rank = 47,
    color = "59df7b",
    runs = 1,
    bestTier = 30,
    score20 = 0,
    score30 = 19,
    score35 = 0,
    score40 = 0,
    score45 = 0,
    runs20 = 0,
    runs30 = 1,
    runs35 = 0,
    runs40 = 0,
    runs45 = 0,
    raidsCompleted = 1,
    bestDungeon = "Halls of Stone",
    bestDungeonEn = "Halls of Stone",
    bestDungeonZh = nil,
    bestDungeonTier = 30,
    bestDungeonScore = 19,
    raidsTotal = 5,
    specs = {
      { role = "dps", spec = "Нечестивость", specID = 252, score = 19 },
    },
  }
  byKey["фростмагх-eversong"] = e
  byKey["фростмагх-вечнаяпесня"] = e

  e = {
    name = "Эксп",
    realmName = "Гордунни",
    realmSlug = "gordunni",
    class = "Воин",
    classFile = "WARRIOR",
    spec = "Неистовство",
    specID = 72,
    score = 19,
    rank = 48,
    color = "5edf7f",
    runs = 1,
    bestTier = 30,
    score20 = 0,
    score30 = 19,
    score35 = 0,
    score40 = 0,
    score45 = 0,
    runs20 = 0,
    runs30 = 1,
    runs35 = 0,
    runs40 = 0,
    runs45 = 0,
    raidsCompleted = 1,
    bestDungeon = "Halls of Stone",
    bestDungeonEn = "Halls of Stone",
    bestDungeonZh = nil,
    bestDungeonTier = 30,
    bestDungeonScore = 19,
    raidsTotal = 5,
    specs = {
      { role = "dps", spec = "Неистовство", specID = 72, score = 19 },
    },
  }
  byKey["эксп-gordunni"] = e
  byKey["эксп-гордунни"] = e

  e = {
    name = "Манабимба",
    realmName = "Король-лич",
    realmSlug = "lich-king",
    class = "Маг",
    classFile = "MAGE",
    spec = "Лед",
    specID = 64,
    score = 18,
    rank = 49,
    color = "64e083",
    runs = 1,
    bestTier = 20,
    score20 = 18,
    score30 = 0,
    score35 = 0,
    score40 = 0,
    score45 = 0,
    runs20 = 1,
    runs30 = 0,
    runs35 = 0,
    runs40 = 0,
    runs45 = 0,
    raidsCompleted = 0,
    bestDungeon = "Halls of Valor",
    bestDungeonEn = "Halls of Valor",
    bestDungeonZh = nil,
    bestDungeonTier = 20,
    bestDungeonScore = 18,
    raidsTotal = 5,
    specs = {
      { role = "dps", spec = "Лед", specID = 64, score = 18 },
    },
  }
  byKey["манабимба-lichking"] = e
  byKey["манабимба-корольлич"] = e

  e = {
    name = "Аетерн",
    realmName = "Азурегос",
    realmSlug = "azuregos",
    class = "Паладин",
    classFile = "PALADIN",
    spec = "Воздаяние",
    specID = 70,
    score = 0,
    rank = 50,
    color = "6de18a",
    runs = 0,
    bestTier = nil,
    score20 = 0,
    score30 = 0,
    score35 = 0,
    score40 = 0,
    score45 = 0,
    runs20 = 0,
    runs30 = 0,
    runs35 = 0,
    runs40 = 0,
    runs45 = 0,
    raidsCompleted = 0,
    bestDungeon = nil,
    bestDungeonEn = nil,
    bestDungeonZh = nil,
    bestDungeonTier = nil,
    bestDungeonScore = nil,
    raidsTotal = 5,
    specs = {

    },
  }
  byKey["аетерн-azuregos"] = e
  byKey["аетерн-азурегос"] = e

  e = {
    name = "Ччерныйрыцар",
    realmName = "Седогрив",
    realmSlug = "greymane",
    class = "Рыцарь смерти",
    classFile = "DEATHKNIGHT",
    spec = "Нечестивость",
    specID = 252,
    score = 0,
    rank = 51,
    color = "72e28e",
    runs = 0,
    bestTier = nil,
    score20 = 0,
    score30 = 0,
    score35 = 0,
    score40 = 0,
    score45 = 0,
    runs20 = 0,
    runs30 = 0,
    runs35 = 0,
    runs40 = 0,
    runs45 = 0,
    raidsCompleted = 0,
    bestDungeon = nil,
    bestDungeonEn = nil,
    bestDungeonZh = nil,
    bestDungeonTier = nil,
    bestDungeonScore = nil,
    raidsTotal = 5,
    specs = {

    },
  }
  byKey["ччерныйрыцар-greymane"] = e
  byKey["ччерныйрыцар-седогрив"] = e

  e = {
    name = "Чеканщик",
    realmName = "Седогрив",
    realmSlug = "greymane",
    class = "Друид",
    classFile = "DRUID",
    spec = "Сила зверя",
    specID = 103,
    score = 0,
    rank = 52,
    color = "77e392",
    runs = 0,
    bestTier = nil,
    score20 = 0,
    score30 = 0,
    score35 = 0,
    score40 = 0,
    score45 = 0,
    runs20 = 0,
    runs30 = 0,
    runs35 = 0,
    runs40 = 0,
    runs45 = 0,
    raidsCompleted = 2,
    bestDungeon = nil,
    bestDungeonEn = nil,
    bestDungeonZh = nil,
    bestDungeonTier = nil,
    bestDungeonScore = nil,
    raidsTotal = 5,
    specs = {

    },
  }
  byKey["чеканщик-greymane"] = e
  byKey["чеканщик-седогрив"] = e

  e = {
    name = "Гроччел",
    realmName = "Седогрив",
    realmSlug = "greymane",
    class = "Чернокнижник",
    classFile = "WARLOCK",
    spec = "Демонология",
    specID = 266,
    score = 0,
    rank = 53,
    color = "7ce396",
    runs = 0,
    bestTier = nil,
    score20 = 0,
    score30 = 0,
    score35 = 0,
    score40 = 0,
    score45 = 0,
    runs20 = 0,
    runs30 = 0,
    runs35 = 0,
    runs40 = 0,
    runs45 = 0,
    raidsCompleted = 2,
    bestDungeon = nil,
    bestDungeonEn = nil,
    bestDungeonZh = nil,
    bestDungeonTier = nil,
    bestDungeonScore = nil,
    raidsTotal = 5,
    specs = {

    },
  }
  byKey["гроччел-greymane"] = e
  byKey["гроччел-седогрив"] = e

  e = {
    name = "Ауфёпта",
    realmName = "Вечная Песня",
    realmSlug = "eversong",
    class = "Охотник",
    classFile = "HUNTER",
    spec = "Выживание",
    specID = 255,
    score = 0,
    rank = 54,
    color = "81e49a",
    runs = 0,
    bestTier = nil,
    score20 = 0,
    score30 = 0,
    score35 = 0,
    score40 = 0,
    score45 = 0,
    runs20 = 0,
    runs30 = 0,
    runs35 = 0,
    runs40 = 0,
    runs45 = 0,
    raidsCompleted = 2,
    bestDungeon = nil,
    bestDungeonEn = nil,
    bestDungeonZh = nil,
    bestDungeonTier = nil,
    bestDungeonScore = nil,
    raidsTotal = 5,
    specs = {

    },
  }
  byKey["ауфёпта-eversong"] = e
  byKey["ауфёпта-вечнаяпесня"] = e

  e = {
    name = "Skizzä",
    realmName = "Ravencrest",
    realmSlug = "ravencrest",
    class = "Друид",
    classFile = "DRUID",
    spec = "Исцеление",
    specID = 105,
    score = 0,
    rank = 55,
    color = "86e59e",
    runs = 0,
    bestTier = nil,
    score20 = 0,
    score30 = 0,
    score35 = 0,
    score40 = 0,
    score45 = 0,
    runs20 = 0,
    runs30 = 0,
    runs35 = 0,
    runs40 = 0,
    runs45 = 0,
    raidsCompleted = 1,
    bestDungeon = nil,
    bestDungeonEn = nil,
    bestDungeonZh = nil,
    bestDungeonTier = nil,
    bestDungeonScore = nil,
    raidsTotal = 5,
    specs = {

    },
  }
  byKey["skizzä-ravencrest"] = e

  e = {
    name = "Дарнук",
    realmName = "Гром",
    realmSlug = "grom",
    class = "Воин",
    classFile = "WARRIOR",
    spec = "Неистовство",
    specID = 72,
    score = 0,
    rank = 56,
    color = "8be5a2",
    runs = 0,
    bestTier = nil,
    score20 = 0,
    score30 = 0,
    score35 = 0,
    score40 = 0,
    score45 = 0,
    runs20 = 0,
    runs30 = 0,
    runs35 = 0,
    runs40 = 0,
    runs45 = 0,
    raidsCompleted = 1,
    bestDungeon = nil,
    bestDungeonEn = nil,
    bestDungeonZh = nil,
    bestDungeonTier = nil,
    bestDungeonScore = nil,
    raidsTotal = 5,
    specs = {

    },
  }
  byKey["дарнук-grom"] = e
  byKey["дарнук-гром"] = e

  e = {
    name = "Фаённа",
    realmName = "Гордунни",
    realmSlug = "gordunni",
    class = "Шаман",
    classFile = "SHAMAN",
    spec = "Исцеление",
    specID = 264,
    score = 0,
    rank = 57,
    color = "90e6a6",
    runs = 0,
    bestTier = nil,
    score20 = 0,
    score30 = 0,
    score35 = 0,
    score40 = 0,
    score45 = 0,
    runs20 = 0,
    runs30 = 0,
    runs35 = 0,
    runs40 = 0,
    runs45 = 0,
    raidsCompleted = 4,
    bestDungeon = nil,
    bestDungeonEn = nil,
    bestDungeonZh = nil,
    bestDungeonTier = nil,
    bestDungeonScore = nil,
    raidsTotal = 5,
    specs = {

    },
  }
  byKey["фаённа-gordunni"] = e
  byKey["фаённа-гордунни"] = e

  e = {
    name = "Килианмёрфи",
    realmName = "Вечная Песня",
    realmSlug = "eversong",
    class = "Охотник",
    classFile = "HUNTER",
    spec = "Стрельба",
    specID = 254,
    score = 0,
    rank = 58,
    color = "95e7aa",
    runs = 0,
    bestTier = nil,
    score20 = 0,
    score30 = 0,
    score35 = 0,
    score40 = 0,
    score45 = 0,
    runs20 = 0,
    runs30 = 0,
    runs35 = 0,
    runs40 = 0,
    runs45 = 0,
    raidsCompleted = 1,
    bestDungeon = nil,
    bestDungeonEn = nil,
    bestDungeonZh = nil,
    bestDungeonTier = nil,
    bestDungeonScore = nil,
    raidsTotal = 5,
    specs = {

    },
  }
  byKey["килианмёрфи-eversong"] = e
  byKey["килианмёрфи-вечнаяпесня"] = e

  e = {
    name = "Тоникокс",
    realmName = "Вечная Песня",
    realmSlug = "eversong",
    class = "Воин",
    classFile = "WARRIOR",
    spec = "Неистовство",
    specID = 72,
    score = 0,
    rank = 59,
    color = "9ae8ae",
    runs = 0,
    bestTier = nil,
    score20 = 0,
    score30 = 0,
    score35 = 0,
    score40 = 0,
    score45 = 0,
    runs20 = 0,
    runs30 = 0,
    runs35 = 0,
    runs40 = 0,
    runs45 = 0,
    raidsCompleted = 1,
    bestDungeon = nil,
    bestDungeonEn = nil,
    bestDungeonZh = nil,
    bestDungeonTier = nil,
    bestDungeonScore = nil,
    raidsTotal = 5,
    specs = {

    },
  }
  byKey["тоникокс-eversong"] = e
  byKey["тоникокс-вечнаяпесня"] = e

  e = {
    name = "Монкёпта",
    realmName = "Вечная Песня",
    realmSlug = "eversong",
    class = "Монах",
    classFile = "MONK",
    spec = "Хмелевар",
    specID = 268,
    score = 0,
    rank = 60,
    color = "9fe8b2",
    runs = 0,
    bestTier = nil,
    score20 = 0,
    score30 = 0,
    score35 = 0,
    score40 = 0,
    score45 = 0,
    runs20 = 0,
    runs30 = 0,
    runs35 = 0,
    runs40 = 0,
    runs45 = 0,
    raidsCompleted = 0,
    bestDungeon = nil,
    bestDungeonEn = nil,
    bestDungeonZh = nil,
    bestDungeonTier = nil,
    bestDungeonScore = nil,
    raidsTotal = 5,
    specs = {

    },
  }
  byKey["монкёпта-eversong"] = e
  byKey["монкёпта-вечнаяпесня"] = e

  e = {
    name = "Glebark",
    realmName = "Ravencrest",
    realmSlug = "ravencrest",
    class = "Охотник",
    classFile = "HUNTER",
    spec = "Выживание",
    specID = 255,
    score = 0,
    rank = 61,
    color = "a4e9b6",
    runs = 0,
    bestTier = nil,
    score20 = 0,
    score30 = 0,
    score35 = 0,
    score40 = 0,
    score45 = 0,
    runs20 = 0,
    runs30 = 0,
    runs35 = 0,
    runs40 = 0,
    runs45 = 0,
    raidsCompleted = 1,
    bestDungeon = nil,
    bestDungeonEn = nil,
    bestDungeonZh = nil,
    bestDungeonTier = nil,
    bestDungeonScore = nil,
    raidsTotal = 5,
    specs = {

    },
  }
  byKey["glebark-ravencrest"] = e

  e = {
    name = "Глебарг",
    realmName = "Вечная Песня",
    realmSlug = "eversong",
    class = "Воин",
    classFile = "WARRIOR",
    spec = "Неистовство",
    specID = 72,
    score = 0,
    rank = 62,
    color = "a9eaba",
    runs = 0,
    bestTier = nil,
    score20 = 0,
    score30 = 0,
    score35 = 0,
    score40 = 0,
    score45 = 0,
    runs20 = 0,
    runs30 = 0,
    runs35 = 0,
    runs40 = 0,
    runs45 = 0,
    raidsCompleted = 1,
    bestDungeon = nil,
    bestDungeonEn = nil,
    bestDungeonZh = nil,
    bestDungeonTier = nil,
    bestDungeonScore = nil,
    raidsTotal = 5,
    specs = {

    },
  }
  byKey["глебарг-eversong"] = e
  byKey["глебарг-вечнаяпесня"] = e

  e = {
    name = "Яточнонегном",
    realmName = "Гром",
    realmSlug = "grom",
    class = "Разбойник",
    classFile = "ROGUE",
    spec = "Ликвидация",
    specID = 259,
    score = 0,
    rank = 63,
    color = "aeeabd",
    runs = 0,
    bestTier = nil,
    score20 = 0,
    score30 = 0,
    score35 = 0,
    score40 = 0,
    score45 = 0,
    runs20 = 0,
    runs30 = 0,
    runs35 = 0,
    runs40 = 0,
    runs45 = 0,
    raidsCompleted = 0,
    bestDungeon = nil,
    bestDungeonEn = nil,
    bestDungeonZh = nil,
    bestDungeonTier = nil,
    bestDungeonScore = nil,
    raidsTotal = 5,
    specs = {

    },
  }
  byKey["яточнонегном-grom"] = e
  byKey["яточнонегном-гром"] = e

  e = {
    name = "Мамакриминал",
    realmName = "Гордунни",
    realmSlug = "gordunni",
    class = "Воин",
    classFile = "WARRIOR",
    spec = "Неистовство",
    specID = 72,
    score = 0,
    rank = 64,
    color = "b3ebc1",
    runs = 0,
    bestTier = nil,
    score20 = 0,
    score30 = 0,
    score35 = 0,
    score40 = 0,
    score45 = 0,
    runs20 = 0,
    runs30 = 0,
    runs35 = 0,
    runs40 = 0,
    runs45 = 0,
    raidsCompleted = 0,
    bestDungeon = nil,
    bestDungeonEn = nil,
    bestDungeonZh = nil,
    bestDungeonTier = nil,
    bestDungeonScore = nil,
    raidsTotal = 5,
    specs = {

    },
  }
  byKey["мамакриминал-gordunni"] = e
  byKey["мамакриминал-гордунни"] = e

  e = {
    name = "Рименис",
    realmName = "Вечная Песня",
    realmSlug = "eversong",
    class = "Паладин",
    classFile = "PALADIN",
    spec = "Защита",
    specID = 66,
    score = 0,
    rank = 65,
    color = "b8ecc5",
    runs = 0,
    bestTier = nil,
    score20 = 0,
    score30 = 0,
    score35 = 0,
    score40 = 0,
    score45 = 0,
    runs20 = 0,
    runs30 = 0,
    runs35 = 0,
    runs40 = 0,
    runs45 = 0,
    raidsCompleted = 0,
    bestDungeon = nil,
    bestDungeonEn = nil,
    bestDungeonZh = nil,
    bestDungeonTier = nil,
    bestDungeonScore = nil,
    raidsTotal = 5,
    specs = {

    },
  }
  byKey["рименис-eversong"] = e
  byKey["рименис-вечнаяпесня"] = e

  e = {
    name = "Ауфёпт",
    realmName = "Король-лич",
    realmSlug = "lich-king",
    class = "Рыцарь смерти",
    classFile = "DEATHKNIGHT",
    spec = "Лед",
    specID = 251,
    score = 0,
    rank = 66,
    color = "bdecc9",
    runs = 0,
    bestTier = nil,
    score20 = 0,
    score30 = 0,
    score35 = 0,
    score40 = 0,
    score45 = 0,
    runs20 = 0,
    runs30 = 0,
    runs35 = 0,
    runs40 = 0,
    runs45 = 0,
    raidsCompleted = 1,
    bestDungeon = nil,
    bestDungeonEn = nil,
    bestDungeonZh = nil,
    bestDungeonTier = nil,
    bestDungeonScore = nil,
    raidsTotal = 5,
    specs = {

    },
  }
  byKey["ауфёпт-lichking"] = e
  byKey["ауфёпт-корольлич"] = e

  e = {
    name = "Ксотлат",
    realmName = "Гордунни",
    realmSlug = "gordunni",
    class = "Охотник на демонов",
    classFile = "DEMONHUNTER",
    spec = "Месть",
    specID = 581,
    score = 0,
    rank = 67,
    color = "c2edcd",
    runs = 0,
    bestTier = nil,
    score20 = 0,
    score30 = 0,
    score35 = 0,
    score40 = 0,
    score45 = 0,
    runs20 = 0,
    runs30 = 0,
    runs35 = 0,
    runs40 = 0,
    runs45 = 0,
    raidsCompleted = 0,
    bestDungeon = nil,
    bestDungeonEn = nil,
    bestDungeonZh = nil,
    bestDungeonTier = nil,
    bestDungeonScore = nil,
    raidsTotal = 5,
    specs = {

    },
  }
  byKey["ксотлат-gordunni"] = e
  byKey["ксотлат-гордунни"] = e

  e = {
    name = "Шади",
    realmName = "Гром",
    realmSlug = "grom",
    class = "Охотник",
    classFile = "HUNTER",
    spec = "Выживание",
    specID = 255,
    score = 0,
    rank = 68,
    color = "c7eed1",
    runs = 0,
    bestTier = nil,
    score20 = 0,
    score30 = 0,
    score35 = 0,
    score40 = 0,
    score45 = 0,
    runs20 = 0,
    runs30 = 0,
    runs35 = 0,
    runs40 = 0,
    runs45 = 0,
    raidsCompleted = 0,
    bestDungeon = nil,
    bestDungeonEn = nil,
    bestDungeonZh = nil,
    bestDungeonTier = nil,
    bestDungeonScore = nil,
    raidsTotal = 5,
    specs = {

    },
  }
  byKey["шади-grom"] = e
  byKey["шади-гром"] = e

  e = {
    name = "Бейбарс",
    realmName = "Гром",
    realmSlug = "grom",
    class = "Паладин",
    classFile = "PALADIN",
    spec = "Воздаяние",
    specID = 70,
    score = 0,
    rank = 69,
    color = "cceed5",
    runs = 0,
    bestTier = nil,
    score20 = 0,
    score30 = 0,
    score35 = 0,
    score40 = 0,
    score45 = 0,
    runs20 = 0,
    runs30 = 0,
    runs35 = 0,
    runs40 = 0,
    runs45 = 0,
    raidsCompleted = 0,
    bestDungeon = nil,
    bestDungeonEn = nil,
    bestDungeonZh = nil,
    bestDungeonTier = nil,
    bestDungeonScore = nil,
    raidsTotal = 5,
    specs = {

    },
  }
  byKey["бейбарс-grom"] = e
  byKey["бейбарс-гром"] = e

  e = {
    name = "Хануд",
    realmName = "Вечная Песня",
    realmSlug = "eversong",
    class = "Охотник",
    classFile = "HUNTER",
    spec = "Стрельба",
    specID = 254,
    score = 0,
    rank = 70,
    color = "d1efd9",
    runs = 0,
    bestTier = nil,
    score20 = 0,
    score30 = 0,
    score35 = 0,
    score40 = 0,
    score45 = 0,
    runs20 = 0,
    runs30 = 0,
    runs35 = 0,
    runs40 = 0,
    runs45 = 0,
    raidsCompleted = 0,
    bestDungeon = nil,
    bestDungeonEn = nil,
    bestDungeonZh = nil,
    bestDungeonTier = nil,
    bestDungeonScore = nil,
    raidsTotal = 5,
    specs = {

    },
  }
  byKey["хануд-eversong"] = e
  byKey["хануд-вечнаяпесня"] = e

  e = {
    name = "Мекна",
    realmName = "Ревущий фьорд",
    realmSlug = "howling-fjord",
    class = "Воин",
    classFile = "WARRIOR",
    spec = "Неистовство",
    specID = 72,
    score = 0,
    rank = 71,
    color = "d6f0dd",
    runs = 0,
    bestTier = nil,
    score20 = 0,
    score30 = 0,
    score35 = 0,
    score40 = 0,
    score45 = 0,
    runs20 = 0,
    runs30 = 0,
    runs35 = 0,
    runs40 = 0,
    runs45 = 0,
    raidsCompleted = 0,
    bestDungeon = nil,
    bestDungeonEn = nil,
    bestDungeonZh = nil,
    bestDungeonTier = nil,
    bestDungeonScore = nil,
    raidsTotal = 5,
    specs = {

    },
  }
  byKey["мекна-howlingfjord"] = e
  byKey["мекна-ревущийфьорд"] = e

  e = {
    name = "Светабум",
    realmName = "Ревущий фьорд",
    realmSlug = "howling-fjord",
    class = "Охотник на демонов",
    classFile = "DEMONHUNTER",
    spec = "Месть",
    specID = 581,
    score = 0,
    rank = 72,
    color = "dbf1e1",
    runs = 0,
    bestTier = nil,
    score20 = 0,
    score30 = 0,
    score35 = 0,
    score40 = 0,
    score45 = 0,
    runs20 = 0,
    runs30 = 0,
    runs35 = 0,
    runs40 = 0,
    runs45 = 0,
    raidsCompleted = 0,
    bestDungeon = nil,
    bestDungeonEn = nil,
    bestDungeonZh = nil,
    bestDungeonTier = nil,
    bestDungeonScore = nil,
    raidsTotal = 5,
    specs = {

    },
  }
  byKey["светабум-howlingfjord"] = e
  byKey["светабум-ревущийфьорд"] = e

  e = {
    name = "Прега",
    realmName = "Голдринн",
    realmSlug = "goldrinn",
    class = "Разбойник",
    classFile = "ROGUE",
    spec = "Головорез",
    specID = 260,
    score = 0,
    rank = 73,
    color = "e0f1e5",
    runs = 0,
    bestTier = nil,
    score20 = 0,
    score30 = 0,
    score35 = 0,
    score40 = 0,
    score45 = 0,
    runs20 = 0,
    runs30 = 0,
    runs35 = 0,
    runs40 = 0,
    runs45 = 0,
    raidsCompleted = 0,
    bestDungeon = nil,
    bestDungeonEn = nil,
    bestDungeonZh = nil,
    bestDungeonTier = nil,
    bestDungeonScore = nil,
    raidsTotal = 5,
    specs = {

    },
  }
  byKey["прега-goldrinn"] = e
  byKey["прега-голдринн"] = e

  e = {
    name = "Ыыаыы",
    realmName = "Вечная Песня",
    realmSlug = "eversong",
    class = "Охотник",
    classFile = "HUNTER",
    spec = "Выживание",
    specID = 255,
    score = 0,
    rank = 74,
    color = "e5f2e9",
    runs = 0,
    bestTier = nil,
    score20 = 0,
    score30 = 0,
    score35 = 0,
    score40 = 0,
    score45 = 0,
    runs20 = 0,
    runs30 = 0,
    runs35 = 0,
    runs40 = 0,
    runs45 = 0,
    raidsCompleted = 1,
    bestDungeon = nil,
    bestDungeonEn = nil,
    bestDungeonZh = nil,
    bestDungeonTier = nil,
    bestDungeonScore = nil,
    raidsTotal = 5,
    specs = {

    },
  }
  byKey["ыыаыы-eversong"] = e
  byKey["ыыаыы-вечнаяпесня"] = e

  e = {
    name = "Антипригорин",
    realmName = "Гордунни",
    realmSlug = "gordunni",
    class = "Шаман",
    classFile = "SHAMAN",
    spec = "Исцеление",
    specID = 264,
    score = 0,
    rank = 75,
    color = "eaf3ed",
    runs = 0,
    bestTier = nil,
    score20 = 0,
    score30 = 0,
    score35 = 0,
    score40 = 0,
    score45 = 0,
    runs20 = 0,
    runs30 = 0,
    runs35 = 0,
    runs40 = 0,
    runs45 = 0,
    raidsCompleted = 2,
    bestDungeon = nil,
    bestDungeonEn = nil,
    bestDungeonZh = nil,
    bestDungeonTier = nil,
    bestDungeonScore = nil,
    raidsTotal = 5,
    specs = {

    },
  }
  byKey["антипригорин-gordunni"] = e
  byKey["антипригорин-гордунни"] = e

  e = {
    name = "Пончикон",
    realmName = "Вечная Песня",
    realmSlug = "eversong",
    class = "Паладин",
    classFile = "PALADIN",
    spec = "Воздаяние",
    specID = 70,
    score = 0,
    rank = 76,
    color = "eff3f1",
    runs = 0,
    bestTier = nil,
    score20 = 0,
    score30 = 0,
    score35 = 0,
    score40 = 0,
    score45 = 0,
    runs20 = 0,
    runs30 = 0,
    runs35 = 0,
    runs40 = 0,
    runs45 = 0,
    raidsCompleted = 0,
    bestDungeon = nil,
    bestDungeonEn = nil,
    bestDungeonZh = nil,
    bestDungeonTier = nil,
    bestDungeonScore = nil,
    raidsTotal = 5,
    specs = {

    },
  }
  byKey["пончикон-eversong"] = e
  byKey["пончикон-вечнаяпесня"] = e

  e = {
    name = "Двэйнджонсон",
    realmName = "Вечная Песня",
    realmSlug = "eversong",
    class = "Разбойник",
    classFile = "ROGUE",
    spec = "Ликвидация",
    specID = 259,
    score = 0,
    rank = 77,
    color = "f4f4f5",
    runs = 0,
    bestTier = nil,
    score20 = 0,
    score30 = 0,
    score35 = 0,
    score40 = 0,
    score45 = 0,
    runs20 = 0,
    runs30 = 0,
    runs35 = 0,
    runs40 = 0,
    runs45 = 0,
    raidsCompleted = 1,
    bestDungeon = nil,
    bestDungeonEn = nil,
    bestDungeonZh = nil,
    bestDungeonTier = nil,
    bestDungeonScore = nil,
    raidsTotal = 5,
    specs = {

    },
  }
  byKey["двэйнджонсон-eversong"] = e
  byKey["двэйнджонсон-вечнаяпесня"] = e

  ForsakenIODB.count = 77
end
